---
- name: Vis Cisco Backup
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Hent hele konfigurationen (show run)
      cisco.ios.ios_command:
        commands: show running-config
      register: config_output

    - name: -------------------------------------------
      debug:
        msg: "Her kommer din backup:"

    - name: Vis konfigurationen
      debug:
        msg: "{{ config_output.stdout_lines }}"
