---
- name: Config Drift Check (Politibetjenten)
  hosts: "{{ target | default('all') }}"
  connection: network_cli
  gather_facts: no
  
  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}" # <--- HUSK TOKEN!
    drift_found: false

  tasks:
    # 1. Hent Sandheden fra NetBox
    - name: Hent Interface data fra NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/?device={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        validate_certs: no
        return_content: yes
      delegate_to: localhost
      register: netbox_data

    # 2. Tjek mod Routeren (Dry Run)
    - name: Sammenlign NetBox mod Router (Check Mode)
      cisco.ios.ios_config:
        lines:
          - description {{ item.description }}
        parents: interface {{ item.name }}
      loop: "{{ netbox_data.json.results }}"
      when: 
        - item.name is defined
        - "'NVI' not in item.name"
        - "'Embedded' not in item.name"
        - "'AppGigabit' not in item.name"
        - "'Vlan' not in item.name"
        - item.description != ""
      check_mode: yes
      register: drift_result

    # 3. Analyser Resultatet (NU MED PÆN TEKST)
    - name: 🚨 DRIFT DETECTED
      debug:
        # Her samler vi det hele på én linje, så Python scriptet viser det pænt
        msg: "Interface {{ item.item.name }} matcher ikke! NetBox siger: '{{ item.item.description }}'"
      loop: "{{ drift_result.results }}"
      when: item.changed

    # 4. Fail tasken hvis der var drift
    - name: Marker opgave som FEJLET hvis der er drift
      fail:
        msg: "Systemet er ikke compliant! Kør en 'Sync NetBox -> Router' for at rette det."
      when: drift_result.changed
