all:
  hosts:
    ISP-CORE1:
      ansible_host: 10.255.255.2  # SKIFT HER: Skriv din routers IP-adresse
      ansible_connection: network_cli
      ansible_network_os: ios    # SKIFT HER: Skriv 'ios' hvis det er Cisco, eller 'vyos' hvis det er VyOS
