all:
  hosts:
    ISP-CORE1:
      ansible_host: 10.255.255.2
      ansible_connection: network_cli
      ansible_network_os: ios
    ISP-EDGE1:  # Tilføj den næste her
      ansible_host: 10.255.255.3 # Den rigtige IP
      ansible_connection: network_cli
      ansible_network_os: ios
    ISP-PE1:  # Og den næste...
      ansible_host: 10.255.255.1
      ansible_connection: network_cli
      ansible_network_os: ios
