---
# PLAY 1: Snyd Ansible og opret en midlertidig liste over de fundne IP'er
- name: Forbered de ukendte IP-adresser
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Tilføj fundne IP'er til midlertidig gruppe
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: discovered_routers
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ onboard_user }}"
        ansible_password: "{{ onboard_password }}"
      loop: "{{ target_ips.split(',') }}"
      when: target_ips is defined

# PLAY 2: Onboarding (Hardware + Interfaces + IPs)
- name: Brownfield Onboarding (Full Sync)
  hosts: discovered_routers
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: 1. Hent ALLE facts (inkl. interfaces) direkte fra enheden
      cisco.ios.ios_facts:
        gather_subset: 
          - hardware
          - interfaces

    - name: 2. Sikr Producent, Rolle og Device Type (samme som før)
      block:
        - netbox.netbox.netbox_manufacturer:
            netbox_url: "{{ netbox_url }}"
            netbox_token: "{{ netbox_token }}"
            validate_certs: no
            data: { name: "Cisco" }
        - netbox.netbox.netbox_device_role:
            netbox_url: "{{ netbox_url }}"
            netbox_token: "{{ netbox_token }}"
            validate_certs: no
            data: { name: "Router", color: "00bcd4" }
        - netbox.netbox.netbox_device_type:
            netbox_url: "{{ netbox_url }}"
            netbox_token: "{{ netbox_token }}"
            validate_certs: no
            data:
              manufacturer: "Cisco"
              model: "{{ ansible_net_model | upper }}"
              slug: "{{ ansible_net_model | lower | replace(' ', '-') }}"
      delegate_to: localhost
      run_once: true

    - name: 3. Opret selve enheden i NetBox
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ ansible_net_hostname }}"
          device_type: "{{ ansible_net_model | upper }}"
          device_role: "Router"
          site: "{{ target_site }}"
          serial: "{{ ansible_net_serialnum }}"
          status: "active"
        state: present
      delegate_to: localhost

    - name: 4. SYNC INTERFACES (Nu bliver det sejt!) 🔌
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          device: "{{ ansible_net_hostname }}"
          name: "{{ item.key }}"
          type: "1000base-t" # Vi gætter på kobber, NetBox retter det hvis modellen kender typen
          enabled: "{{ item.value.enabled }}"
          description: "{{ item.value.description | default('') }}"
        state: present
      loop: "{{ ansible_net_interfaces | dict2items }}"
      delegate_to: localhost
      # Vi gør dette for alle interfaces fundet på switchen

    - name: 5. SYNC IP-ADRESSER 🌐
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          address: "{{ item.value.ipv4[0].address }}/{{ item.value.ipv4[0].mask }}"
          status: "active"
          assigned_object:
            device: "{{ ansible_net_hostname }}"
            name: "{{ item.key }}"
        state: present
      # Vi looper kun over interfaces der rent faktisk har en IPv4 adresse
      loop: "{{ ansible_net_interfaces | dict2items }}"
      when: item.value.ipv4 is defined
      delegate_to: localhost
