---
# PLAY 1: Forbered IP'er
- name: "Forbered de ukendte IP-adresser"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Tilføj fundne IP'er til midlertidig gruppe"
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: discovered_routers
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ onboard_user }}"
        ansible_password: "{{ onboard_password }}"
      loop: "{{ target_ips.split(',') }}"
      when: target_ips is defined

# PLAY 2: Deep Discovery (VTP Optimized)
- name: "Brownfield Onboarding (VTP Logic)"
  hosts: discovered_routers
  gather_facts: no

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: "1. Hent hardware og interface facts (Alle switches)"
      cisco.ios.ios_facts:
        gather_subset: 
          - hardware
          - interfaces

    - name: "1b. Hent VLAN informationer (Kun fra én switch pga. VTP) 🔍"
      cisco.ios.ios_vlans:
        state: gathered
      register: vlan_output
      run_once: true # <--- Vigtigt: Vi stoler på VTP-listen fra den første switch

    - name: "2. Basis Opsætning i NetBox"
      block:
        - netbox.netbox.netbox_manufacturer:
            netbox_url: "{{ netbox_url }}"
            netbox_token: "{{ netbox_token }}"
            validate_certs: no
            data: { name: "Cisco" }
        - netbox.netbox.netbox_vlan_group:
            netbox_url: "{{ netbox_url }}"
            netbox_token: "{{ netbox_token }}"
            validate_certs: no
            data:
              name: "{{ target_site | upper }}-VLANS"
              slug: "{{ target_site | lower }}-vlans"
              scope_type: "dcim.site"
              scope: { name: "{{ target_site | upper }}" }
      delegate_to: localhost
      run_once: true

    - name: "3. Opret/Opdater selve Switchen (Alle skal oprettes!)"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ ansible_net_hostname }}"
          device_type: "{{ ansible_net_model | upper }}"
          device_role: "Router"
          site: "{{ target_site }}"
          serial: "{{ ansible_net_serialnum }}"
          status: "active"
        state: present
      delegate_to: localhost

    - name: "4. SYNC VLANs (Køres kun én gang pga. VTP) 🏷️"
      netbox.netbox.netbox_vlan:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          name: "{{ item.name }}"
          vid: "{{ item.vlan_id }}"
          site: "{{ target_site }}"
          vlan_group: "{{ target_site | upper }}-VLANS"
          status: "active"
        state: present
      loop: "{{ vlan_output.gathered | default([]) }}"
      when: "item.vlan_id | int >= 2 and item.vlan_id | int < 1000"
      delegate_to: localhost
      run_once: true # <--- Vi behøver kun oprette VLAN-listen i NetBox én gang

    - name: "5. SYNC PREFIXES (Matematik: 10.50.[VLAN-300].0/24) 🌐"
      netbox.netbox.netbox_prefix:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          prefix: "10.50.{{ (item.vlan_id | int) - 300 }}.0/24"
          site: "{{ target_site }}"
          status: "active"
          vlan: 
            vid: "{{ item.vlan_id }}"
            vlan_group: "{{ target_site | upper }}-VLANS"
        state: present
      loop: "{{ vlan_output.gathered | default([]) }}"
      when: "item.vlan_id | int >= 300 and item.vlan_id | int < 1000"
      delegate_to: localhost
      run_once: true # <--- Prefixes er også de samme for hele sitet

    - name: "6. SYNC INTERFACES (Alle porte på alle switches) 🔌"
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          device: "{{ ansible_net_hostname }}"
          name: "{{ item.key }}"
          type: "1000base-t"
          enabled: "{{ item.value.enabled | default(true) }}"
        state: present
      loop: "{{ ansible_net_interfaces | dict2items }}"
      delegate_to: localhost
