- name: Hent data fra router til NetBox
  hosts: all
  gather_facts: no

  tasks:
    - name: Hent facts (Eksempel for Cisco - ret hvis du har andet mærke)
      cisco.ios.ios_facts:
        gather_subset: all
      register: device_facts

    - name: Opret interfaces fra routeren i NetBox
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.name }}"
          type: "1000base-t" # Ret til f.eks. virtual hvis det er sub-interfaces
          enabled: "{{ item.enabled }}"
          mtu: "{{ item.mtu }}"
          description: "{{ item.description | default('') }}"
        state: present
      loop: "{{ device_facts.ansible_facts.ansible_net_interfaces }}"
      when: device_facts.ansible_facts.ansible_net_interfaces is defined
