- name: Hent data fra router til NetBox
  hosts: all
  gather_facts: no

  tasks:
    - name: Hent facts fra router
      cisco.ios.ios_facts:
        gather_subset: all
      register: device_facts

    - name: 1. Sikr at routeren findes i NetBox
      netbox.netbox.netbox_device:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          name: "{{ inventory_hostname }}"
          serial: "{{ device_facts.ansible_facts.ansible_net_serialnum }}"
          device_type: "Cisco 1900"
          device_role: "Router"
          site: "Eksamen"
          status: active
        state: present

    - name: 2. Opret interfaces i NetBox
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.key }}"
          type: "{{ 'virtual' if 'Vlan' in item.key or 'Loopback' in item.key else '1000base-t' }}"
          enabled: "{{ true if item.value.operstatus == 'up' else false }}"
          mtu: "{{ item.value.mtu }}"
          description: "{{ item.value.description if item.value.description else '' }}"
        state: present
      loop: "{{ device_facts.ansible_facts.ansible_net_interfaces | dict2items }}"

    - name: 3. Opret og tildel IP-adresser til interfaces
      netbox.netbox.netbox_ip_address:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          # Her trækker vi IP og subnet ud fra router-data
          address: "{{ item.1.address }}/{{ item.1.subnet }}"
          status: active
          assigned_object:
            device: "{{ inventory_hostname }}"
            name: "{{ item.0.key }}"
        state: present
      # Her bruger vi 'lookup' til at flette interfaces og deres IP'er sammen korrekt
      loop: "{{ lookup('ansible.builtin.subelements', device_facts.ansible_facts.ansible_net_interfaces | dict2items, 'value.ipv4', {'skip_missing': True}) }}"
      loop_control:
        label: "{{ item.1.address }}/{{ item.1.subnet }} på {{ item.0.key }}"

    - name: 4. Sæt Loopback1 som Primary IP i NetBox
      netbox.netbox.netbox_device:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          name: "{{ inventory_hostname }}"
          # Her finder vi IP-adressen for Loopback1 fra dine router-facts
          primary_ip4: "{{ device_facts.ansible_facts.ansible_net_interfaces.Loopback1.ipv4.0.address }}/32"
        state: present
      # Vi kører kun denne opgave, hvis routeren faktisk har en Loopback1 med en IP
      when: 
        - device_facts.ansible_facts.ansible_net_interfaces.Loopback1 is defined
        - device_facts.ansible_facts.ansible_net_interfaces.Loopback1.ipv4 | length > 0
