- name: Hent data fra router til NetBox
  hosts: all
  gather_facts: no

  tasks:
    - name: Hent facts fra router
      cisco.ios.ios_facts:
        gather_subset: all
      register: device_facts

    - name: 1. Sikr at routeren findes i NetBox
      netbox.netbox.netbox_device:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          name: "{{ inventory_hostname }}"
          serial: "{{ device_facts.ansible_facts.ansible_net_serialnum }}"
          device_type: "Cisco 1900"
          device_role: "Router"
          site: "Eksamen"
          status: active
        state: present

    - name: 2. Opret interfaces i NetBox
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.key }}"
          type: "{{ 'virtual' if 'Vlan' in item.key or 'Loopback' in item.key else '1000base-t' }}"
          enabled: "{{ true if item.value.operstatus == 'up' else false }}"
          mtu: "{{ item.value.mtu }}"
          description: "{{ item.value.description if item.value.description else '' }}"
        state: present
      loop: "{{ device_facts.ansible_facts.ansible_net_interfaces | dict2items }}"
      when: device_facts.ansible_facts.ansible_net_interfaces is defined
