---
- name: Synkronisering af Router-data til NetBox
  hosts: all
  gather_facts: no

  tasks:
    # --- DEL 1: GRUNDLAGET ---
    - name: 1. Hent facts fra routeren
      cisco.ios.ios_facts:
        gather_subset: all
      register: device_facts

    - name: 2. Sikr at enheden eksisterer i NetBox (DCIM)
      netbox.netbox.netbox_device:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          name: "{{ inventory_hostname }}"
          serial: "{{ device_facts.ansible_facts.ansible_net_serialnum }}"
          device_type: "Cisco 1900"
          device_role: "Router"
          site: "Eksamen"
          status: active
        state: present

    # --- DEL 2: INTERFACES (Layer 2/3 porte) ---
    - name: 3. Opret alle interfaces på enheden
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.key }}"
          type: "{{ 'virtual' if 'Vlan' in item.key or 'Loopback' in item.key else '1000base-t' }}"
          enabled: "{{ true if item.value.operstatus == 'up' else false }}"
          description: "{{ item.value.description if item.value.description else '' }}"
        state: present
      loop: "{{ device_facts.ansible_facts.ansible_net_interfaces | dict2items }}"

    # --- DEL 3: IPAM (VLANs) ---
    - name: 4. Opret VLANs i den globale IPAM liste
      netbox.netbox.netbox_vlan:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          vid: "{{ item.key | regex_replace('Vlan', '') | int }}"
          name: "{{ item.value.description if item.value.description else 'VLAN' + item.key | regex_replace('Vlan', '') }}"
          status: active
          site: "Eksamen"
        state: present
      loop: "{{ device_facts.ansible_facts.ansible_net_interfaces | dict2items }}"
      when: "'Vlan' in item.key and item.key != 'Vlan1'"

    # --- DEL 4: IP-ADRESSER ---
    - name: 5. Tildel IP-adresser til de rigtige interfaces
      netbox.netbox.netbox_ip_address:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          address: "{{ item.1.address }}/{{ item.1.subnet }}"
          status: active
          assigned_object:
            device: "{{ inventory_hostname }}"
            name: "{{ item.0.key }}"
        state: present
      loop: "{{ lookup('ansible.builtin.subelements', device_facts.ansible_facts.ansible_net_interfaces | dict2items, 'value.ipv4', {'skip_missing': True}) }}"

    - name: 6. Opret kabler baseret på CDP/LLDP naboer
      netbox.netbox.netbox_cable:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: "{{ inventory_hostname }}"
            name: "{{ item.key }}"
          termination_b_type: dcim.interface
          termination_b:
            device: "{{ item.value[0].host | split('.') | first }}" # Vi tager kun det første navn før et punktum
            name: "{{ item.value[0].port }}"
          type: cat6 # Eller hvad du foretrækker
          status: connected
        state: present
      # Vi kører dette loop over alle naboer fundet af ios_facts
      loop: "{{ device_facts.ansible_facts.ansible_net_neighbors | dict2items }}"
      when: device_facts.ansible_facts.ansible_net_neighbors is defined
