---
- name: BGP til NetBox via API (Robust version)
  hosts: all
  gather_facts: no

  tasks:
    - name: 1. Hent BGP summary fra Cisco
      cisco.ios.ios_command:
        commands: "show ip bgp summary"
      register: bgp_summary

    - name: 2. Find ASN og Naboer via Regex
      set_fact:
        local_as: "{{ bgp_summary.stdout[0] | regex_search('local AS number (\\d+)', '\\1') | first | default('65000') }}"
        bgp_neighbors: "{{ bgp_summary.stdout[0] | regex_findall('(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+\\d+\\s+(\\d+)') }}"

    - name: 3. Find Device ID i NetBox automatisk
      uri:
        url: "https://10.36.1.80/api/dcim/devices/?name={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
      register: device_lookup

    - name: 4. Opret ASN i NetBox
      uri:
        url: "https://10.36.1.80/api/ipam/asns/"
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          asn: "{{ local_as }}"
          rir: 1  # Tjek at du har en RIR i NetBox med ID 1
        status_code: [201, 400]
        validate_certs: no

    - name: 5. Opret BGP Session i NetBox
      uri:
        # Prøv denne sti hvis du bruger BGP-plugin'et
        url: "https://10.36.1.80/api/plugins/bgp/session/" 
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          name: "BGP_to_{{ item[0] }}"
          device: "{{ device_lookup.json.results[0].id }}"
          local_as: "{{ local_as }}"
          remote_as: "{{ item[1] }}"
          remote_address: "{{ item[0] }}/32"
          status: "active"
        status_code: [201, 400, 404]
        validate_certs: no
      loop: "{{ bgp_neighbors }}"
      when: 
        - bgp_neighbors | length > 0
        - device_lookup.json.count > 0
