---
- name: BGP til NetBox - Endelig Version
  hosts: all
  gather_facts: no

  tasks:
    - name: 1. Hent BGP summary fra Cisco
      cisco.ios.ios_command:
        commands: "show ip bgp summary"
      register: bgp_summary

    - name: 2. Find ASN og Naboer
      set_fact:
        local_as_num: "{{ bgp_summary.stdout[0] | regex_search('local AS number (\\d+)', '\\1') | first | default('65000') }}"
        bgp_neighbors: "{{ bgp_summary.stdout[0] | regex_findall('(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+\\d+\\s+(\\d+)') }}"

    - name: 3. Opret/Sikr ASN i NetBox (Bruger RIR ID 1)
      uri:
        url: "https://10.36.1.80/api/ipam/asns/"
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          asn: "{{ local_as_num }}"
          rir: 1  # Bekræftet ID fra dit link!
        status_code: [201, 400]
        validate_certs: no

    - name: 4. Find det interne ID for vores ASN
      uri:
        url: "https://10.36.1.80/api/ipam/asns/?asn={{ local_as_num }}"
        method: GET
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
      register: asn_lookup

    - name: 5. Find det interne ID for Routeren
      uri:
        url: "https://10.36.1.80/api/dcim/devices/?name={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
      register: device_lookup

    - name: 6. Opret BGP Session (Med fejl-visning)
      uri:
        url: "https://10.36.1.80/api/plugins/bgp/session/"
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          name: "BGP_to_{{ item[0] }}"
          device: "{{ device_lookup.json.results[0].id }}"
          local_as: "{{ asn_lookup.json.results[0].id }}"
          remote_as: "{{ item[1] | int }}" # Sikrer at AS sendes som et tal
          remote_address: "{{ item[0] }}"
          status: "active"
        # Vi fjerner 400 her, så Ansible STOPPER og viser fejlen hvis noget er galt
        status_code: [201] 
        validate_certs: no
      loop: "{{ bgp_neighbors }}"
      register: session_output
      ignore_errors: yes # Så vi kan køre debug bagefter

    - name: 7. VIS FEJL HVIS SESSION MANGLER
      debug:
        msg: "NetBox svarede: {{ item.json }}"
      loop: "{{ session_output.results }}"
      when: item.failed
