---
- name: Hent BGP naboer og dokumentér i NetBox
  hosts: all
  gather_facts: no

  tasks:
    - name: 1. Hent BGP summary fra Cisco
      cisco.ios.ios_command:
        commands: "show ip bgp summary"
      register: bgp_summary

    - name: 2. Find ASN og Naboer
      set_fact:
        # Finder det lokale AS nummer
        local_as: "{{ bgp_summary.stdout[0] | regex_search('local AS number (\\d+)', '\\1') | first | default(none) }}"
        # Finder nabo-IP'er og deres AS
        bgp_neighbors: "{{ bgp_summary.stdout[0] | regex_findall('(\\d+\\.\\d+\\.\\d+\\.\\d+)\\s+\\d+\\s+(\\d+)') }}"

    - name: 3. Opret AS-nummer i NetBox
      netbox.netbox.netbox_asn:  # <--- Rettet fra netbox_as_number
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          asn: "{{ local_as }}"
          description: "Lokalt AS for {{ inventory_hostname }}"
          rir: "Internal" # NetBox kræver ofte en RIR (f.eks. RFC 1918 eller Internal)
        state: present
      when: local_as is not none

    - name: 4. Opret BGP Session i NetBox
      netbox.netbox.netbox_bgp_session:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          local_as: "{{ local_as }}"
          remote_as: "{{ item[1] }}"
          remote_address: "{{ item[0] }}"
          name: "BGP_to_{{ item[0] }}"
          status: "active"
        state: present
      loop: "{{ bgp_neighbors }}"
      when: 
        - local_as is not none
        - bgp_neighbors | length > 0
