---
- name: Sync Router Interfaces til NetBox
  hosts: all
  gather_facts: no
  connection: network_cli
  
  tasks:
    - name: Hent facts fra Router (Læs interfaces)
      cisco.ios.ios_facts:
        gather_subset:
          - interfaces
          - all

    - name: Opret/Opdater Interfaces i NetBox
      netbox.netbox.netbox_device_interface:
        netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
        netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
        data:
          device: "{{ inventory_hostname }}"
          name: "{{ item.key }}"
          # Type er obligatorisk i NetBox, vi sætter en standard
          type: "1000base-t" 
          
          # --- HER ER RETTELSEN ---
          # Vi bruger 'default' filtre, så den ikke crasher hvis data mangler
          
          # Hvis 'oper_status' er 'up', så er den enabled. Ellers disabled.
          enabled: "{{ item.value.oper_status | default('down') == 'up' }}"
          
          # Hvis MTU mangler (fx på VLANs), sæt den til 1500
          mtu: "{{ item.value.mtu | default(1500) | int }}"
          
          description: "{{ item.value.description | default('Importeret fra Ansible') }}"
        state: present
      loop: "{{ ansible_net_interfaces | dict2items }}"
      delegate_to: localhost
