---
- name: Sync Topology (Legacy Mode) -> NetBox
  hosts: all
  gather_facts: no
  connection: network_cli

  vars:
    netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: Tænd CDP
      cisco.ios.ios_config:
        lines:
          - cdp run

    - name: Hent CDP Neighbors Detail (Raw Text)
      cisco.ios.ios_command:
        commands: show cdp neighbors detail
      register: cdp_raw

    - name: Opret Kabel i NetBox (Fixed)
      netbox.netbox.netbox_cable:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: no
        data:
          # --- ENDE A (Denne Router) ---
          termination_a_type: dcim.interface  # <--- SÅDAN HER! (Flyttet ud)
          termination_a:
            device: "{{ inventory_hostname }}"
            name: "{{ item | regex_search('Interface: ([^,]+),', '\\1') | first }}"
          
          # --- ENDE B (Naboen) ---
          termination_b_type: dcim.interface  # <--- SÅDAN HER! (Flyttet ud)
          termination_b:
            device: "{{ item | regex_search('Device ID: ([^\\r\\n]+)', '\\1') | first | split('.') | first }}"
            name: "{{ item | regex_search('Port ID \\(outgoing port\\): ([^\\r\\n]+)', '\\1') | first }}"
            
          status: connected
          type: cat6
          length: 10
          length_unit: m
          
      # Loop igennem hver blok af tekst
      loop: "{{ cdp_raw.stdout[0].split('-------------------------') }}"
      delegate_to: localhost
      ignore_errors: yes 
      when: "'Device ID:' in item"
