---
- name: Sync NetBox -> Router (SAFE MODE)
  hosts: all
  connection: network_cli
  gather_facts: no
  
  vars:
    netbox_url: "https://10.36.1.80"
    netbox_token: "DdQEEtl583idIa6TtA3avkxsyhxncqPirUO198BM" # Husk token!
    
  tasks:
    - name: Hent Interface data fra NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/interfaces/?device={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: "application/json"
        validate_certs: no
        return_content: yes
      delegate_to: localhost
      register: netbox_data

    - name: Opdater KUN Beskrivelser (Rører ikke status/IP)
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description | default(omit) }}"
            # Vi har fjernet 'enabled' linjen her, så den aldrig slukker noget!
        state: merged
      loop: "{{ netbox_data.json.results }}"
      when: item.name is defined

    - name: Gem konfiguration
      cisco.ios.ios_config:
        save_when: modified
