---
- name: Hent VRF'er og kobl interfaces rigtigt
  hosts: all
  gather_facts: no

  tasks:
    - name: 1. Hent vrf forwarding linjer fra config
      cisco.ios.ios_command:
        commands: "show running-config | include vrf forwarding"
      register: vrf_lines

    - name: 2. Find unikke VRF navne
      set_fact:
        found_vrfs: "{{ vrf_lines.stdout[0] | regex_findall('vrf forwarding (\\S+)') | unique }}"

    - name: 3. Opret VRF'erne i NetBox
      netbox.netbox.netbox_vrf:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          name: "{{ item }}"
          rd: "65000:10" # Du kan rette RD til det rigtige her
        state: present
      loop: "{{ found_vrfs }}"
      when: found_vrfs | length > 0

    - name: 4. Hent interface-tilknytning via VRF tabel
      cisco.ios.ios_command:
        commands: "show ip vrf interfaces"
      register: vrf_interfaces

    - name: 5. Kobl interfaces til VRF i NetBox (Med navne-fix)
      netbox.netbox.netbox_device_interface:
        netbox_url: "https://10.36.1.80"
        netbox_token: "lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
        data:
          device: "{{ inventory_hostname }}"
          # Her fixer vi Gi -> GigabitEthernet og Vl -> Vlan
          name: "{{ item.split()[0] | replace('Gi', 'GigabitEthernet') | replace('Vl', 'Vlan') }}"
          vrf: "CUST"
        state: present
      # Vi springer overskriften over og tager kun linjer med 'CUST'
      loop: "{{ vrf_interfaces.stdout[0].splitlines()[1:] }}"
      when: "'CUST' in item"
