---
- name: BGP til NetBox - Komplet Integration
  hosts: all
  gather_facts: no

  tasks:
    - name: 1. Hent BGP og Interface data fra Cisco
      cisco.ios.ios_facts:
        gather_subset: 
          - interfaces
          - protocols
      register: router_data

    - name: 2. Find ASN ID og Device ID i NetBox
      uri:
        url: "https://10.36.1.80/api/{{ item.path }}/?{{ item.query }}={{ item.value }}"
        method: GET
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        validate_certs: no
      loop:
        - { path: 'ipam/asns', query: 'asn', value: '65000' }
        - { path: 'dcim/devices', query: 'name', value: "{{ inventory_hostname }}" }
      register: lookups

    - name: 3. Opret/Hent naboens IP i NetBox (IPAM)
      uri:
        url: "https://10.36.1.80/api/ipam/ip-addresses/"
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          address: "{{ item[0] }}/32"
          status: "active"
        status_code: [201, 400]
        validate_certs: no
      # Vi tager nabo-IP'erne fra BGP-summary (regex fra tidligere)
      loop: "{{ router_data.ansible_facts.ansible_net_neighbors | dict2items | map(attribute='key') | list | zip(router_data.ansible_facts.ansible_net_neighbors | dict2items | map(attribute='value.remote_as') | list) | list }}"
      register: neighbor_ips

    - name: 4. Opret BGP Session med alle relationer
      uri:
        url: "https://10.36.1.80/api/plugins/bgp/session/"
        method: POST
        headers:
          Authorization: "Token lG3FMb0IagPwT1X0ZU53i4ZiNgutwfIdauh24n2f"
        body_format: json
        body:
          name: "BGP_to_{{ item.item[0] }}"
          device: "{{ lookups.results[1].json.results[0].id }}"
          local_as: "{{ lookups.results[0].json.results[0].id }}"
          remote_as: "{{ lookups.results[0].json.results[0].id }}" # iBGP bruger samme ID
          # Vi bruger naboens IP
          remote_address: "{{ item.json.id if item.status == 201 else (item.json.address | default(1)) }}"
          # Vi finder den lokale Loopback IP (f.eks. 10.255.255.x)
          local_address: "{{ router_data.ansible_facts.ansible_net_interfaces['Loopback1'].ipv4[0].address if 'Loopback1' in router_data.ansible_facts.ansible_net_interfaces else none }}"
          status: "active"
        status_code: [201, 400]
        validate_certs: no
      loop: "{{ neighbor_ips.results }}"
      when: neighbor_ips.results | length > 0
