---
- name: Hent facts og opdater NetBox
  hosts: all
  connection: network_cli
  gather_facts: yes

  tasks:
    - name: Tving installation af pynetbox i kørselmiljøet
      pip:
        name: pynetbox
        state: present
      delegate_to: localhost
      run_once: true

    - name: Sørg for at Device findes i NetBox
      netbox.netbox.netbox_device:
        netbox_url: "{{ nb_url }}"
        netbox_token: "{{ nb_token }}"
        data:
          name: "{{ inventory_hostname }}"
          device_type: "Cisco 1900"
          device_role: "Router"
          site: "Home-Lab"
          status: "active"
        state: present
      delegate_to: localhost
